export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";

export const GET_MOVIES_FAILURE = "GET_MOVIES_FAILURE";

export const GET_RECENT_MOVIES_SUCCESS = "GET_RECENT_MOVIES_SUCCESS";

export const GET_RECENT_MOVIES_FAILURE = "GET_RECENT_MOVIES_FAILURE";

export const GET_MOVIE_THUMBNAILS_SUCCESS = "GET_MOVIE_THUMBNAILS_SUCCESS";

export const GET_MOVIE_THUMBNAILS_FAILURE = "GET_MOVIE_THUMBNAILS_FAILURE";

export const UPDATE_CURRENT_MOVIE_SUCCESS = "UPDATE_CURRENT_MOVIE_SUCCESS";

export const UPDATE_CURRENT_MOVIE_FAILURE = "UPDATE_CURRENT_MOVIE_FAILURE";

export const GET_SEARCHABLE_MOVIES_SUCCESS = "GET_SEARCHABLE_MOVIES_SUCCESS";

export const GET_SEARCHABLE_MOVIES_FAILURE = "GET_SEARCHABLE_MOVIES_FAILURE";